# -*- coding: utf-8 -*-
"""question_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jejAwQf0Fe7UhKNKzyuZgvBZXFA4iMaR
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import os, json

router = APIRouter()

# 경로 설정
BASE_PATH = os.path.join(os.path.dirname(__file__), '..', '..', '..')
METRICS_FILE = os.path.join(BASE_PATH, 'data', 'question', 'question_model_metrics.json')
MODEL_DIR = os.path.join(BASE_PATH, 'models', 'question')

# 요청 데이터 형식
class TrainRequest(BaseModel):
    newModelName: str
    epoch: int
    batchSize: int

@router.post("/questionModelTrain")
def train_question_model(data: TrainRequest):
    model_name = data.newModelName
    epoch = data.epoch
    batch_size = data.batchSize

    # 실제 훈련 로직은 여기에 연결 (생략)
    # ex: train_question_model_fn(model_name, epoch, batch_size)

    # 훈련된 모델 디렉토리 생성
    model_path = os.path.join(MODEL_DIR, model_name)
    try:
        os.makedirs(model_path, exist_ok=False)  # 이미 있으면 예외 발생
    except FileExistsError:
        raise HTTPException(status_code=400, detail="이미 존재하는 모델 이름입니다.")

    # 실제 훈련 후 계산된 ROUGE 점수 (예시 값)
    dummy_rouge_score = 0.7324

    # 모델 메트릭 기록
    new_entry = {
        "modelName": model_name,
        "epoch": epoch,
        "batchSize": batch_size,
        "rouge_score": round(dummy_rouge_score, 4)
    }

    # 기존 메트릭 파일 읽고 추가
    metrics = []
    if os.path.exists(METRICS_FILE):
        with open(METRICS_FILE, encoding="utf-8") as f:
            metrics = json.load(f)

    metrics.append(new_entry)

    with open(METRICS_FILE, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2, ensure_ascii=False)

    return {"message": f"'{model_name}' 모델 훈련 및 등록 완료. (ROUGE: {new_entry['rouge_score']})"}