# -*- coding: utf-8 -*-
"""question_predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_k4NBOWhoBogiHmA1jzvhSgg8MzEzVAA
"""

from fastapi import APIRouter
from pydantic import BaseModel
from app.services.question.question_predictor import predict_question

router = APIRouter()

class QuestionRequest(BaseModel):
    paragraph: str
    version: str

@router.post("/predict_question")
def predict(input_data: QuestionRequest):
    paragraph = input_data.paragraph
    version = input_data.version

    try:
        questions = predict_question(paragraph, version)
        return {
            "input": paragraph,
            "version": version,
            "generated_questions": questions
        }
    except Exception as e:
        return {"error": str(e)}